export const clients = [
  {
    id: 1,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 2,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 3,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 4,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 5,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 6,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 7,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 40000,
  },
  {
    id: 8,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 200000,
  },
  {
    id: 9,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 80000,
  },
  {
    id: 10,
    name: "client1",
    address: "kathmandu-4",
    description: "this is the donation box",
    req_amt: 100000,
    col_amt: 500000,
  },
];
