import AdminNavbar from "@/components/AdminNavbar";
import "../globals.css";
import AdminSidebar from "@/components/AdminSidebar";
import AdminContextProviders from "@/libs/AdminContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AdminContextProviders>
          <div className="lg:flex">
            <div className="lg:w-fit w-full">
              <AdminSidebar />
            </div>
            <div className="lg:flex-grow ">
              <AdminNavbar />
              {children}
            </div>
          </div>
        </AdminContextProviders>
      </body>
    </html>
  );
}
