import AdminNavbar from '@/components/AdminNavbar'
import '../globals.css'
import AdminSidebar from '@/components/AdminSidebar'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex'>
          <div className='w-[15%]'>
          <AdminSidebar/>
          </div>
          <div className='flex-grow'>
        <AdminNavbar/>
        {children}
          </div>
        </div>
        </body>
    </html>
  )
}
