import Navbar from "@/components/Navbar";
import SupabaseProvider from "../../SupabaseComponents/SupabaseProvider";
import "../globals.css";

import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <div>
            <Navbar />

            {children}
            <Footer />
          </div>
        </SupabaseProvider>
      </body>
    </html>
  );
}
